//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaFramework.Presentation.View.GlobalText {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialog {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Verion.Presentation.View.GlobalText.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ButtonAddDescription {
            get {
                return ResourceManager.GetString("ButtonAddDescription", resourceCulture);
            }
        }
        
        public static string ButtonCancelDescription {
            get {
                return ResourceManager.GetString("ButtonCancelDescription", resourceCulture);
            }
        }
        
        public static string ButtonClearDescription {
            get {
                return ResourceManager.GetString("ButtonClearDescription", resourceCulture);
            }
        }
        
        public static string ButtonDeleteDescription {
            get {
                return ResourceManager.GetString("ButtonDeleteDescription", resourceCulture);
            }
        }
        
        public static string ButtonDetailsDescription {
            get {
                return ResourceManager.GetString("ButtonDetailsDescription", resourceCulture);
            }
        }
        
        public static string ButtonDiscardUpdateDescription {
            get {
                return ResourceManager.GetString("ButtonDiscardUpdateDescription", resourceCulture);
            }
        }
        
        public static string ButtonEditDescription {
            get {
                return ResourceManager.GetString("ButtonEditDescription", resourceCulture);
            }
        }
        
        public static string ButtonOpenEditDescription {
            get {
                return ResourceManager.GetString("ButtonOpenEditDescription", resourceCulture);
            }
        }
        
        public static string ButtonSaveUpdateDescription {
            get {
                return ResourceManager.GetString("ButtonSaveUpdateDescription", resourceCulture);
            }
        }
        
        public static string MessageConfirmDelete {
            get {
                return ResourceManager.GetString("MessageConfirmDelete", resourceCulture);
            }
        }
        
        public static string OptionButtonCancel {
            get {
                return ResourceManager.GetString("OptionButtonCancel", resourceCulture);
            }
        }
        
        public static string OptionButtonNo {
            get {
                return ResourceManager.GetString("OptionButtonNo", resourceCulture);
            }
        }
        
        public static string OptionButtonOk {
            get {
                return ResourceManager.GetString("OptionButtonOk", resourceCulture);
            }
        }
        
        public static string OptionButtonYes {
            get {
                return ResourceManager.GetString("OptionButtonYes", resourceCulture);
            }
        }
        
        public static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
    }
}
