//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaFramework.Presentation.View {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Verion.Presentation.View.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ValueValidatorInvalidValueMessage {
            get {
                return ResourceManager.GetString("ValueValidatorInvalidValueMessage", resourceCulture);
            }
        }
        
        public static string ValueValidatorNullErrorMessage {
            get {
                return ResourceManager.GetString("ValueValidatorNullErrorMessage", resourceCulture);
            }
        }
        
        public static string ValueValidatorUnexpectedValueMessage {
            get {
                return ResourceManager.GetString("ValueValidatorUnexpectedValueMessage", resourceCulture);
            }
        }
        
        public static string ArgumentUnexpectedType {
            get {
                return ResourceManager.GetString("ArgumentUnexpectedType", resourceCulture);
            }
        }
        
        public static string ConcurrentPresentationModelStartup {
            get {
                return ResourceManager.GetString("ConcurrentPresentationModelStartup", resourceCulture);
            }
        }
        
        public static string PresenterCanceledExceptionMessage {
            get {
                return ResourceManager.GetString("PresenterCanceledExceptionMessage", resourceCulture);
            }
        }
        
        public static string PresenterExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("PresenterExceptionDefaultMessage", resourceCulture);
            }
        }
        
        public static string PresenterRewindExceptionMessage {
            get {
                return ResourceManager.GetString("PresenterRewindExceptionMessage", resourceCulture);
            }
        }
        
        public static string ConteudoPrincipalNulo {
            get {
                return ResourceManager.GetString("ConteudoPrincipalNulo", resourceCulture);
            }
        }
        
        public static string NovosBotoesPrimariosNulos {
            get {
                return ResourceManager.GetString("NovosBotoesPrimariosNulos", resourceCulture);
            }
        }
        
        public static string NovosBotoesSecundariosNulos {
            get {
                return ResourceManager.GetString("NovosBotoesSecundariosNulos", resourceCulture);
            }
        }
        
        public static string ModeloApresentacaoBotaoPower_Desligado {
            get {
                return ResourceManager.GetString("ModeloApresentacaoBotaoPower_Desligado", resourceCulture);
            }
        }
        
        public static string ModeloApresentacaoBotaoPower_Ligado {
            get {
                return ResourceManager.GetString("ModeloApresentacaoBotaoPower_Ligado", resourceCulture);
            }
        }
        
        public static string ModeloApresentacaoBotaoPower_Desabilitado {
            get {
                return ResourceManager.GetString("ModeloApresentacaoBotaoPower_Desabilitado", resourceCulture);
            }
        }
    }
}
